### ISSUE TITLE
Accuracy 

### ISSUE THREAD

**Issue by showbit01** [shicaiwei123/patch_based_cnn#12]
@shicaiwei123 I tested the model patch ,depth and both but these are not accurate on high light condition sometimes in low light condition...how to do the same any idea?

**Comment by shicaiwei123** [comment]
In my view, these are not surprising. The generalization ability is exactly the problem of the current face anti-spoofing methods.

Maybe you can search for some ideas from the latest research about domain adaptation, such as Single-Side Domain Generalization for Face Anti-Spoofing，

Or cross-view anti-spoofing, or multimodal anti-spoofing



At 2022-05-20 14:38:02, "Shobhit Sharma" ***@***.***> wrote:

@shicaiwei123 I tested the model patch ,depth and both but these are not accurate on high light condition sometimes in low light condition...how to do the same any idea?

**Comment by showbit01** [comment]
Thanks for replying,yeah will try to do what you said and to fuse these layers for more robust..

**Comment by showbit01** [comment]
> 



> In my view, these are not surprising. The generalization ability is exactly the problem of the current face anti-spoofing methods. Maybe you can search for some ideas from the latest research about domain adaptation, such as Single-Side Domain Generalization for Face Anti-Spoofing， Or cross-view anti-spoofing, or multimodal anti-spoofing At 2022-05-20 14:38:02, "Shobhit Sharma" ***@***.***> wrote: @shicaiwei123 I tested the model patch ,depth and both but these are not accurate on high light condition sometimes in low light condition...how to do the same any idea? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

Hey thanks for the insights,I have went throught these papers like in single side domain generailzation the real faces should be more compact in feature space and fake diverse and did the adverserial for that but again in real world we cant sure of certain domains real faces may be diverse....and they do require 3-4 spoofing database i have only one casia mfsd data...would you please help me in this...
